version: 2

sources:
  - name: raw_data_circle
    description: raw data sport wear from LW
    tables:
      - name: raw_cc_stock
        description: stock of the products from LW
      - name: raw_cc_sales
        description: sales of the products
        tests:
          - unique:
              column_name: "(product_id || '-' || date_date)"